POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "User 1",
  "email": "user1@example.com",
  "password": "123456"
}

###

POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "User 2",
  "email": "user2@example.com",
  "password": "654321"
}

###

POST http://localhost:3333/auth
Content-Type: application/json

{
  "email": "user2@example.com",
  "password": "654321"
}

###
PATCH http://localhost:3333/auth/refresh
Content-Type: application/json

{
  "email": "user2@example.com",
  "password": "654321"
}

###
GET http://localhost:3333/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMjM3ZTY5Zi1hYTk2LTQwNGYtOTJjNS0yNTA3ZjQ0ZTY2NGUiLCJpYXQiOjE2ODMyMTIwNTMsImV4cCI6MTY4MzIxNTY1M30.P_xyOfez6QcE3l0KjhDt48sroEBD1C0M9lRwJgg-8zc