POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@example.com",
  "password": "123456"
}

###

POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "User 2",
  "email": "user2@example.com",
  "password": "654321"
}

###

POST http://localhost:3333/auth
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

###
PATCH http://localhost:3333/auth/refresh
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

###
GET http://localhost:3333/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJhM2U4OWNmZi1iOTU0LTQyMGUtODcwNy02YjZmMjY1MWI4ZWUiLCJpYXQiOjE2ODMyNDgxMzUsImV4cCI6MTY4MzI1MTczNX0.y4w3xB1kovyTJxCTr64IKecnqjVKn6ufy1Uq_tmEUus

###
POST http://localhost:3333/gyms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJhM2U4OWNmZi1iOTU0LTQyMGUtODcwNy02YjZmMjY1MWI4ZWUiLCJpYXQiOjE2ODMyNDgxMzUsImV4cCI6MTY4MzI1MTczNX0.y4w3xB1kovyTJxCTr64IKecnqjVKn6ufy1Uq_tmEUus
